name = "Breakout"
uuid = "1a604a49-2ee9-46dc-8073-86211d0c62e4"
version = "1.0.0"
authors = ["Asvin Goel <github@telematique.eu>"]
license = "MIT"
description = "A simple Breakout clone for fun and reinforcement learning on internal game state"
keywords = ["reinforcement-learning", "game", "breakout"]

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
CommonRLInterface = "d842c3ba-07a1-494f-bbec-f5741b0a3e98"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
SimpleDirectMediaLayer = "98e33af6-2ee5-5afd-9e75-cbc738b767c4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.10"
Colors = "0.13"
CommonRLInterface = "0.3"
FileIO = "1.17"
Images = "0.26"
SimpleDirectMediaLayer = "0.5"
